#!/bin/sh
#
# Compiles all *.py files and copies both the *.py and the *.pyc files to
# the directory specified on the command-line.
#
# Usage:  Install <directory>
#
# Note: Only run from within the directory containing this script.

INSTDIR=$1

if [ $# -ne 1 ]; then
	echo "Usage: $0 <directory>"
	exit 1
fi

if [ ! -d $INSTDIR ]; then
	echo "$INSTDIR is not a directory"
	exit 1
fi

python -c 'import compileall; compileall.compile_dir(".")'

for file in `ls *.py *.pyc`
do
	cp $file $INSTDIR
	chmod ug+w $INSTDIR/$file
done
#
# Warranty Disclaimer and Copyright Notice
# 
#  THE JACKSON LABORATORY MAKES NO REPRESENTATION ABOUT THE SUITABILITY OR 
#  ACCURACY OF THIS SOFTWARE OR DATA FOR ANY PURPOSE, AND MAKES NO WARRANTIES, 
#  EITHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A 
#  PARTICULAR PURPOSE OR THAT THE USE OF THIS SOFTWARE OR DATA WILL NOT 
#  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS, OR OTHER RIGHTS.  
#  THE SOFTWARE AND DATA ARE PROVIDED "AS IS".
# 
#  This software and data are provided to enhance knowledge and encourage 
#  progress in the scientific community and are to be used only for research 
#  and educational purposes.  Any reproduction or use for commercial purpose 
#  is prohibited without the prior express written permission of the Jackson 
#  Laboratory.
# 
# Copyright © 1996, 1999, 2002 by The Jackson Laboratory
# All Rights Reserved
#

